// shared 公开 API 入口（全量收口，01 原则10 不豁免）
// 组件经 index.ts 聚合导出，消费方一律走 @/shared，禁止深路径穿透。
export * from './composables/useApiRequest'
export * from './composables/useAuth'
export * from './composables/useFavorites'
export * from './composables/useLatestRequest'
export * from './composables/usePlans'
export * from './composables/useProfileSnapshot'
export * from './composables/useWaitForRenderer'
export * from './constants/api'
export * from './constants/chart'
export * from './constants/colors'
export * from './constants/forecast'
export * from './constants/ui'
export * from './layout/config'
export * from './layout/useGCS'
export * from './layout/useTheme'
export * from './utils/boundedMap'
export * from './utils/crs'
export * from './utils/errorHandler'
export * from './utils/facilityLabels'
export * from './utils/gcsFeedback'
export * from './utils/loadStatic'
export * from './utils/logger'
export * from './utils/perfReporter'
export * from './utils/pointFeature'
export * from './utils/responseEnvelope'
export * from './utils/safeStorage'
export * from './utils/spatialIndex'
// 收口：组件聚合导出
export { default as EmptyState } from './components/EmptyState.vue'
export { default as ErrorBoundary } from './components/ErrorBoundary.vue'
export { default as GCSModal } from './components/GCSModal.vue'
export { default as GCSToast } from './components/GCSToast.vue'
export { default as PaginatedListPanel } from './components/PaginatedListPanel.vue'
export { default as PanelTitle } from './components/PanelTitle.vue'
export { default as PlanSaveModal } from './components/PlanSaveModal.vue'
export { default as SliderSelectCard } from './components/SliderSelectCard.vue'
